# Generated by Django 3.0.5 on 2020-04-08 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Post',
        ),
    ]
