# Generated by Django 3.0.5 on 2020-04-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_review', '0002_auto_20200408_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='evaluate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
